# Generated by Django 5.0.5 on 2024-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='access_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
