# Generated by Django 5.0.5 on 2024-05-07 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0002_alter_siteuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
