# Generated by Django 5.0.5 on 2024-05-07 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0003_alter_siteuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='access_token',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
