# Generated by Django 5.0.5 on 2024-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0006_siteuser_email_siteuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isShared',
            field=models.BooleanField(default=False),
        ),
    ]
