# Generated by Django 5.0.5 on 2024-05-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linkshare", "0010_image_alter_link_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="rasm",
        ),
    ]
