# Generated by Django 5.0.5 on 2024-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkshare", "0013_remove_image_category_remove_image_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
