# Generated by Django 5.0.5 on 2024-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0015_alter_siteuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='savedlinks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
