# Generated by Django 5.0.5 on 2024-06-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshare', '0017_remove_siteuser_savedlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='globalcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linkshare.globalcategory'),
        ),
    ]
